from __future__ import annotations

import re

from ..llm.base import LLMBackend
from ..tools.base import ToolResult
from . import impact_analysis

_SKIP_NOTE_RE = re.compile(r"^_(.+)_$", re.MULTILINE)

_CONDENSE_MAX_CHARS = 6000
_COMBINED_PROMPT_CHAR_CEILING = 60000  # ~15K tokens at ~4 chars/token


def _condense(text: str, max_chars: int = _CONDENSE_MAX_CHARS) -> str:
    if len(text) <= max_chars:
        return text
    head_len = max_chars * 2 // 3
    tail_len = max_chars - head_len
    omitted = len(text) - max_chars
    return f"{text[:head_len]}\n... [{omitted} characters omitted] ...\n{text[-tail_len:]}"


def _format_tool_section(result: ToolResult) -> str:
    if not result.available:
        body = f"SKIPPED: {result.skipped_reason}"
    else:
        body = _condense(result.stdout.strip() or "(no output)")
        if result.stderr.strip():
            body += f"\n[stderr]\n{_condense(result.stderr.strip())}"
    return f"## {result.tool}\n$ {' '.join(result.command)}\n\n{body}\n"


def _build_findings_prompt(target: str, results: list[ToolResult]) -> str:
    sections = "\n".join(_format_tool_section(r) for r in results)
    return (
        "You are a security analyst summarizing automated reconnaissance results for an "
        "authorized penetration test. Analyze the raw tool output below and write a concise "
        "narrative summary. Flag anything interesting: open ports, exposed services and "
        "versions, discovered subdomains, web technologies, likely misconfigurations, and any "
        "findings a pentester should investigate further. Do not fabricate findings that "
        "aren't supported by the output. Plain text, no markdown formatting.\n\n"
        f"Target: {target}\n\n"
        f"{sections}"
    )


def _summarize_with_fallback(backend: LLMBackend, target: str, results: list[ToolResult]) -> str:
    prompt = _build_findings_prompt(target, results)
    if len(prompt) <= _COMBINED_PROMPT_CHAR_CEILING:
        return backend.summarize(prompt)

    # Prompt too large even after per-tool condensation: summarize passive/active
    # stages separately, then merge the two summaries into one narrative.
    mid = len(results) // 2
    passive_prompt = _build_findings_prompt(target, results[:mid])
    active_prompt = _build_findings_prompt(target, results[mid:])
    passive_summary = backend.summarize(passive_prompt)
    active_summary = backend.summarize(active_prompt)
    merge_prompt = (
        "Merge these two partial recon summaries into one cohesive narrative summary, "
        "plain text, no markdown formatting.\n\n"
        f"Summary A:\n{passive_summary}\n\nSummary B:\n{active_summary}"
    )
    return backend.summarize(merge_prompt)


def extract_ai_summary(markdown_text: str) -> str:
    """Pull just the '## AI Summary' section back out of a rendered report --
    used to serve the dashboard a small, fast payload instead of making it
    download the entire report (which embeds every tool's full raw output,
    verified in practice to reach tens of MB for a target with a large
    waybackurls archive) just to show a few paragraphs of narrative text.
    Stops at whichever of "## Potential Impact Analysis" or "## Raw Findings"
    comes first -- the impact-analysis section is deterministic/rule-based,
    not LLM output, so it must not get swept into what's labeled "ai_summary"."""
    start_marker = "## AI Summary"
    start = markdown_text.find(start_marker)
    if start == -1:
        return ""
    after_start = start + len(start_marker)
    end_positions = [
        pos for pos in (
            markdown_text.find("## Potential Impact Analysis", after_start),
            markdown_text.find("## Raw Findings", after_start),
        ) if pos != -1
    ]
    end = min(end_positions) if end_positions else -1
    section = markdown_text[after_start:end] if end != -1 else markdown_text[after_start:]
    return section.strip()


def extract_first_skip_note(markdown_text: str) -> str | None:
    """Mirrors the dashboard's original client-side extraction: only the
    first skip note, used as one generic "why is this tool missing" message
    for any tool absent from the manifest. Only needed as a fallback for
    reports generated before write_ai_summary() started persisting this
    directly."""
    start = markdown_text.find("## Raw Findings")
    if start == -1:
        return None
    end = markdown_text.find("### ", start)
    raw = markdown_text[start:end] if end != -1 else markdown_text[start:]
    match = _SKIP_NOTE_RE.search(raw)
    return match.group(1) if match else None


def build(target: str, results: list[ToolResult], backend: LLMBackend, skip_notes: list[str] | None = None) -> str:
    ai_summary = _summarize_with_fallback(backend, target, results)
    impact_section = impact_analysis.render_markdown(impact_analysis.analyze(results))

    lines = [
        f"# Recon Summary: {target}",
        "",
        f"_Generated by reconai using the {backend.name} backend._",
        "",
        "## AI Summary",
        "",
        ai_summary,
        "",
    ]
    if impact_section:
        lines += [impact_section, ""]
    lines += [
        "## Raw Findings",
        "",
    ]
    for note in skip_notes or []:
        lines += [f"_{note}_", ""]

    for result in results:
        lines.append(f"### {result.tool}")
        lines.append(f"`{' '.join(result.command)}`")
        lines.append("")
        if not result.available:
            lines.append(f"**Skipped:** {result.skipped_reason}")
        else:
            lines.append("```")
            lines.append(result.stdout.strip() or "(no output)")
            if result.stderr.strip():
                lines.append("")
                lines.append("--- STDERR ---")
                lines.append(result.stderr.strip())
            lines.append("```")
            if result.extra.get("screenshot_path"):
                lines.append("")
                lines.append(f"![screenshot]({result.extra['screenshot_path']})")
        lines.append("")

    return "\n".join(lines)
