from __future__ import annotations

from ..llm.base import LLMBackend
from ..tools.base import ToolResult

_CONDENSE_MAX_CHARS = 6000
_COMBINED_PROMPT_CHAR_CEILING = 60000  # ~15K tokens at ~4 chars/token


def _condense(text: str, max_chars: int = _CONDENSE_MAX_CHARS) -> str:
    if len(text) <= max_chars:
        return text
    head_len = max_chars * 2 // 3
    tail_len = max_chars - head_len
    omitted = len(text) - max_chars
    return f"{text[:head_len]}\n... [{omitted} characters omitted] ...\n{text[-tail_len:]}"


def _format_tool_section(result: ToolResult) -> str:
    if not result.available:
        body = f"SKIPPED: {result.skipped_reason}"
    else:
        body = _condense(result.stdout.strip() or "(no output)")
        if result.stderr.strip():
            body += f"\n[stderr]\n{_condense(result.stderr.strip())}"
    return f"## {result.tool}\n$ {' '.join(result.command)}\n\n{body}\n"


def _build_findings_prompt(target: str, results: list[ToolResult]) -> str:
    sections = "\n".join(_format_tool_section(r) for r in results)
    return (
        "You are a security analyst summarizing automated reconnaissance results for an "
        "authorized penetration test. Analyze the raw tool output below and write a concise "
        "narrative summary. Flag anything interesting: open ports, exposed services and "
        "versions, discovered subdomains, web technologies, likely misconfigurations, and any "
        "findings a pentester should investigate further. Do not fabricate findings that "
        "aren't supported by the output. Plain text, no markdown formatting.\n\n"
        f"Target: {target}\n\n"
        f"{sections}"
    )


def _summarize_with_fallback(backend: LLMBackend, target: str, results: list[ToolResult]) -> str:
    prompt = _build_findings_prompt(target, results)
    if len(prompt) <= _COMBINED_PROMPT_CHAR_CEILING:
        return backend.summarize(prompt)

    # Prompt too large even after per-tool condensation: summarize passive/active
    # stages separately, then merge the two summaries into one narrative.
    mid = len(results) // 2
    passive_prompt = _build_findings_prompt(target, results[:mid])
    active_prompt = _build_findings_prompt(target, results[mid:])
    passive_summary = backend.summarize(passive_prompt)
    active_summary = backend.summarize(active_prompt)
    merge_prompt = (
        "Merge these two partial recon summaries into one cohesive narrative summary, "
        "plain text, no markdown formatting.\n\n"
        f"Summary A:\n{passive_summary}\n\nSummary B:\n{active_summary}"
    )
    return backend.summarize(merge_prompt)


def build(target: str, results: list[ToolResult], backend: LLMBackend, skip_note: str | None = None) -> str:
    ai_summary = _summarize_with_fallback(backend, target, results)

    lines = [
        f"# Recon Summary: {target}",
        "",
        f"_Generated by reconai using the {backend.name} backend._",
        "",
        "## AI Summary",
        "",
        ai_summary,
        "",
        "## Raw Findings",
        "",
    ]
    if skip_note:
        lines += [f"_{skip_note}_", ""]

    for result in results:
        lines.append(f"### {result.tool}")
        lines.append(f"`{' '.join(result.command)}`")
        lines.append("")
        if not result.available:
            lines.append(f"**Skipped:** {result.skipped_reason}")
        else:
            lines.append("```")
            lines.append(result.stdout.strip() or "(no output)")
            if result.stderr.strip():
                lines.append("")
                lines.append("--- STDERR ---")
                lines.append(result.stderr.strip())
            lines.append("```")
            if result.extra.get("screenshot_path"):
                lines.append("")
                lines.append(f"![screenshot]({result.extra['screenshot_path']})")
        lines.append("")

    return "\n".join(lines)
