from __future__ import annotations

import datetime
from pathlib import Path

from fpdf import FPDF

# The core Helvetica font FPDF uses here only supports Latin-1 -- verified for
# real: a plain curly quote (as commonly appears in scraped page content)
# raises FPDFUnicodeEncodingException and crashes rendering entirely. Rather
# than embed a Unicode TTF font (a real dependency just for this optional,
# best-effort export), unsupported characters are replaced instead -- exact
# fidelity of raw scraped text in the PDF isn't the point; the full-fidelity
# artifact is summary.md/the per-tool .txt files, which are never touched.
_MAX_CHARS = 200_000


def _latin1_safe(text: str) -> str:
    return text.encode("latin-1", errors="replace").decode("latin-1")


def render(markdown_text: str, output_path: Path, target: str) -> Path:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_margins(left=15, top=15, right=15)

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Automated Recon Report", new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.set_font("Helvetica", "I", 10)
    current_date = datetime.datetime.now().strftime("%Y-%m-%d")
    pdf.cell(0, 10, _latin1_safe(f"Target: {target} | Generated by reconai on {current_date}"),
             new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(10)

    body = markdown_text
    if len(body) > _MAX_CHARS:
        # A PDF isn't meant to be the complete forensic artifact -- that's
        # summary.md and the per-tool .txt files, both already written and
        # untouched by this cap. Without it, a target with a very large raw
        # dump (e.g. waybackurls output can run into tens of MB) would make
        # FPDF render an enormous number of pages, one line at a time.
        omitted = len(body) - _MAX_CHARS
        body = f"{body[:_MAX_CHARS]}\n\n... [{omitted} characters omitted -- see summary.md for the full report] ..."

    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 6, _latin1_safe(body))

    pdf.output(str(output_path))
    return output_path
