from __future__ import annotations

import datetime
from pathlib import Path

from fpdf import FPDF


def render(markdown_text: str, output_path: Path, target: str) -> Path:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_margins(left=15, top=15, right=15)

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Automated Recon Report", new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.set_font("Helvetica", "I", 10)
    current_date = datetime.datetime.now().strftime("%Y-%m-%d")
    pdf.cell(0, 10, f"Target: {target} | Generated by reconai on {current_date}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(10)

    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 6, markdown_text)

    pdf.output(str(output_path))
    return output_path
